### ISSUE TITLE
Empty response with gunicorn

### ISSUE THREAD

**Issue by nikitph** [singingwolfboy/flask-sse#1]
how do we configure sse for dev env? i m able to send but get empty res on client

*_var source = new EventSource("{{ url_for('sse.stream') }}");
*_        source.addEventListener('greeting', function (event) {
            var data = JSON.parse(event.data);
            $('#dropdown3').append('<a href="#" class="collection-item"> f </a>');
        }, false);

**Comment by nikitph** [comment]
using gevent instead of gunicorn gets me moving

**Comment by singingwolfboy** [comment]
@nikitph Can you clarify your question? I'm not sure what you're asking, or how I can help you.

**Comment by apoorv-nag** [comment]
Without Gunicorn it will work fine. Run your app in another port. Gunicorn spawns multiple threads based on your CPU cores and do not keep a persistent connect.
