### ISSUE TITLE
Redis blocking connection issue

### ISSUE THREAD

**Issue by MMohan1** [singingwolfboy/flask-sse#14]
**Problem** -> We are implemented the SSE events on our prod app, We faced issue that if we hit multiple time more the 15 times application got stuck and didn't got any response. 
Our Application have below config-
Nginx as Proxy Server
Twisted as wsgi to Run Flask App

**Issue** -> When i debugged this issue i find out that when we are calling the /stream endpoint it's tring to listen the Redis messages using below code 
`for pubsub_message in pubsub.listen()`
here the  `pubsub.listen()` is a blocking call until didn't got any message. In this case the Flask one thread got busy with this operation, if we hit multiple time all the flask app thread will be busy with the given operation. So the app will be unreachable in some time.

**Solution** -> While we are making connection to Redis we need to provide the socket_timeout to timeout the listen operation after certain time.
For more details go through here - https://github.com/andymccurdy/redis-py/issues/225

I submitted a merge Request on this issue. Please find the link -
https://github.com/singingwolfboy/flask-sse/pull/13

**Comment by singingwolfboy** [comment]
Closed due to author's inactivity on #13.
