### ISSUE TITLE
flask+mod_wsgi+flask-sse is possible>?

### ISSUE THREAD

**Issue by giriannamalai** [singingwolfboy/flask-sse#18]
I tried with websockets ended with incompatable with apache issue. Shall I use this with mod_wsgi?
Is gevent could run in apache_mod_wsgi?

**Comment by singingwolfboy** [comment]
I have no idea how well Apache handles websockets. A quick search led me to [apache-websocket](https://github.com/disconnect/apache-websocket), which might help. I have no idea how (or if) flask-sse would work with that.

I recommend that you try it, and then add another comment to this GitHub issue with the result! Other people may have this same question in the future, and I'm sure they would appreciate an answer, one way or the other.

**Comment by giriannamalai** [comment]
Ok. I will try and get back here...!

**Comment by cdcformatc** [comment]
I am using Flask on Apache with mod_wsgi and Flask-SSE. I can confirm it works.

**Comment by giriannamalai** [comment]
Oh.. This is promising..! I will try it!
Thanks
