### ISSUE TITLE
Proper Design for Flask-Login Support?

### ISSUE THREAD

**Issue by jerryji** [singingwolfboy/flask-sse#19]
Sorry this is more like a question rather than an issue report -- I'm just out of idea who to turn to when my SO question ( [https://stackoverflow.com/questions/54379538/how-to-support-flask-sse-access-control](https://stackoverflow.com/questions/54379538/how-to-support-flask-sse-access-control) ) is not getting much view / answer.

Basically I need to support both public and private SSE ( unlike in my SO question, I finally decided to use channel private.<user_id> instead of route ). Right now I'm monkey-patching Flask-SSE with --

```
        @stream_with_context
        def generator():
            if channel.startswith('private.'): # private area
                channel_user_id = channel.replace('private.', '').lower()
                if not (current_user and current_user.is_authenticated and 
                        current_user.get_id().lower() == channel_user_id):
                    raise StopIteration
            else:
                for message in self.messages(channel=channel):
                    yield str(message)
```

I'm not sure if it's a good way or even a right way. I'd really appreciate any pointer.

**Comment by singingwolfboy** [comment]
Why not set up your access control like this?

```python
@sse.before_request 
def check_access():
    channel = request.args.get("channel") or "sse"
    if channel.startswith("private."):
        if current_user.is_anonymous:
            abort(401)
        user_id = channel[8:]
        if current_user.get_id() != user_id:
            abort(403)
```

Does that work for you?

**Comment by jerryji** [comment]
Thanks @singingwolfboy It works!

Actually I'm not sure what I did wrong the first time that something wasn't working
