### ISSUE TITLE
Unable to run: Error Is Redis running?

### ISSUE THREAD

**Issue by Rahul-RB** [singingwolfboy/flask-sse#20]
I have a system running on IP: `192.168.247.129`. I have redis running on that. Upon doing `ps aux | grep redis` I get:

`redis     50690  0.2  0.1  50152  3808 ?        Ssl  10:55   0:01 /usr/bin/redis-server 192.168.247.129:6379`

(The IP is different since I've put that in `/etc/redis/redis.conf`)

I tried running the quickstart code and its not working.

**Comment by singingwolfboy** [comment]
Did you set the `REDIS_URL` correctly?
