### ISSUE TITLE
sse.before_request not working

### ISSUE THREAD

**Issue by GabrieleCalarota** [singingwolfboy/flask-sse#25]
Hi, I've imported default blueprint sse from flask_sse

after 
```app.register_blueprint(sse, url_prefix='/events')

@sse.before_request
def check_access():
    if request.args.get("channel") == "analytics" and not g.user.is_admin():
        abort(403)
```

Running the app with flask and accessing URL at http://localhost:5000/events sse.before request will not be run, don't know why. I've checked with debugger.

Has this something to do with flask:see or with blueprints in general?

**Comment by singingwolfboy** [comment]
This is related to blueprints in general. [See the API documentation for `Blueprint.before_request`.](https://flask.palletsprojects.com/en/1.1.x/api/#flask.Blueprint.before_request)

**Comment by GabrieleCalarota** [comment]
@singingwolfboy I understand, but before closing.
I found this workaround:
```
@app.before_request
def before_request():
    if request.path == "/events":
        if current_user.is_anonymous:
            abort(403)
```

But of course is not optimal, because I want a before_app event triggered only for sse non for the entire flask app.
Btw: app.before_request of course works as expected!

**Comment by GabrieleCalarota** [comment]
I'm gonna close it now,
very stupid mistake (not well explained in the doc.
**Need to put @see.before_request and every other changes BEFORE registering to the flask app**
Example:
```
@sse.before_request
def check_access():
    if request.args.get("channel") == "analytics" and not g.user.is_admin():
        abort(403)

app.register_blueprint(sse, url_prefix="/events")
```
Thanks btw for the hint @singingwolfboy
