### ISSUE TITLE
Possible Enhancement to Disable SSE in Development

### ISSUE THREAD

**Issue by frankV** [singingwolfboy/flask-sse#5]
David, following up on our conversation about the possibility of disabling the extension to quickly switch back to using the flask development server.

What do you think about using a config variable to control it? I haven't looked at the source code much yet, but maybe there's a simple way to toggle initialization of the extension by looking for the existence of a particular app config variable? It would have to gracefully handle the blueprint too, since it's most likely there will be some `url_for`s in an app's templates and that would throw `BuildError`s.

Let me know what you think about this direction. I'd be happy to offer a PR if you agree.

**Comment by singingwolfboy** [comment]
Why not handle this outside of the extension itself? For example:

```python
if not app.debug:
    app.register_blueprint(sse, url_prefix='/stream')
```

**Comment by frankV** [comment]
That's a good idea...
