### ISSUE TITLE
subscribe channel name based on session 

### ISSUE THREAD

**Issue by vinnitu** [singingwolfboy/flask-sse#9]
I need send personal events to user session

https://github.com/singingwolfboy/flask-sse/blob/a5c6afe12cd3c29c90588ad8a2c698c829af6572/flask_sse.py#L150

How can I do it?

**Comment by singingwolfboy** [comment]
Name the channel based on something specific to the user. Maybe the user ID? You may also want to implement [access control](http://flask-sse.readthedocs.io/en/latest/advanced.html#access-control) so that only the specified user can read events from the channel.

**Comment by simanacci** [comment]
@singingwolfboy Hi, suppose a user is checking several channels does it mean having different EventSource's   
`const source = new EventSource("{{ url_for('sse.stream', channel=one) }}");`  
`const source = new EventSource("{{ url_for('sse.stream', channel=two) }}");`  
or looping through a list of users and directly sending the message to each user .i.e `channel=user.id`?
